import type { LiteralsMap } from "./types";

export const en: LiteralsMap = {
  "common.welcome": "Welcome",
  "common.cta": "Continue",
  "common.loading": "Loading...",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "nav.features": "Features",
  "nav.pricing": "Pricing",
  "nav.blog": "Blog",
  "nav.about": "About",
  "nav.login": "Login",
  "nav.getStarted": "Get Started",
  "hero.title": "Scale Your Creative Service with Confidence",
  "hero.titleHighlight": "Service",
  "hero.subtitle": "The all-in-one platform to automate your workflow, manage high-value clients, and centralize your agency operations in one clean interface.",
  "hero.ctaPrimary": "Start Free Trial",
  "hero.ctaSecondary": "Watch Demo",
  "hero.trustedBy": "Trusted by 2000+ agency owners",
  "section.why.tag": "Why us",
  "section.why.title": "Why Agencies Need Us",
  "section.why.subtitle": "Tools built so your team can close more deals with less friction.",
  "section.why.card1.title": "Scaling Operations",
  "section.why.card1.desc": "Manage projects, teams, and clients from one place without losing control.",
  "section.why.card2.title": "Manage Closers' Efficiency",
  "section.why.card2.desc": "Automate meetings, links, and reminders so your closers focus on selling.",
  "section.why.card3.title": "Automated Billing",
  "section.why.card3.desc": "Recurring revenue, retainers, and one-off invoices in one integrated flow.",
  "section.how.tag": "How closers win",
  "section.how.title": "How Closers Win",
  "section.how.subtitle": "High-quality offers, streamlined meetings, and transparent commissions.",
  "section.how.card1.title": "High-Quality Offers",
  "section.how.card1.desc": "Get exclusive access to vetted, high-ticket agency offers with proven funnels and marketing collateral that actually converts.",
  "section.how.card2.title": "Streamlined Meetings",
  "section.how.card2.desc": "Automatic Zoom link generation, calendar syncing, and automated reminders. No more manual link sending or missed appointments.",
  "section.how.card3.title": "Transparent Commissions",
  "section.how.card3.desc": "Track your earnings in real-time. Full visibility into every commission, payout schedule, and bonus structure in your personal dashboard.",
  "section.freelancers.tag": "For freelancers",
  "section.freelancers.title": "How we help freelancers",
  "section.freelancers.subtitle": "Tools so you work solo but not alone: projects, billing, and a professional presence.",
  "section.freelancers.card1.title": "Everything in one place",
  "section.freelancers.card1.desc": "Manage projects, clients, and billing from a single platform without switching tools.",
  "section.freelancers.card2.title": "Friction-free billing",
  "section.freelancers.card2.desc": "Create invoices, recurring charges, and automatic reminders. Get paid on time with less paperwork.",
  "section.freelancers.card3.title": "Professional presence",
  "section.freelancers.card3.desc": "Client portal, proposals, and deliverables in one place. Look like an agency without the complexity.",
  "section.everything.title": "Everything you need to scale",
  "section.everything.subtitle": "Project management, client portal, and billing in one platform.",
  "section.everything.card1.title": "Project Management",
  "section.everything.card1.desc": "Track every pixel and deadline with intuitive task boards, Gantt charts, and custom workflows tailored for design teams.",
  "section.everything.card2.title": "White-Label Client Portal",
  "section.everything.card2.desc": "Provide a professional experience with a custom-branded portal where clients can review designs, give feedback, and approve milestones.",
  "section.everything.card3.title": "Automated Billing",
  "section.everything.card3.desc": "Manage subscriptions, retainers, and one-off project invoices automatically. Get paid on time with built-in payment integrations.",
  "section.pricing.title": "Choose your growth plan",
  "section.pricing.subtitle": "Plans for every stage of your agency.",
  "section.pricing.starter.label": "Small Agency",
  "section.pricing.starter.name": "Starter",
  "section.pricing.starter.desc": "Perfect for freelancers starting their agency journey.",
  "section.pricing.starter.cta": "Get Started",
  "section.pricing.pro.label": "Growing Teams",
  "section.pricing.pro.name": "Pro Agency",
  "section.pricing.pro.desc": "Everything you need to manage a serious design business.",
  "section.pricing.pro.cta": "Choose Plan",
  "section.pricing.pro.badge": "Most popular",
  "section.pricing.enterprise.label": "Large Enterprise",
  "section.pricing.enterprise.name": "Enterprise",
  "section.pricing.enterprise.desc": "Bespoke features for large agencies scaling fast.",
  "section.pricing.enterprise.cta": "Contact Sales",
  "section.pricing.feature.projects": "Unlimited projects",
  "section.pricing.feature.portal": "Client portal",
  "section.pricing.feature.billing": "Automated billing",
  "section.pricing.feature.support": "Email support",
  "section.pricing.feature.priority": "Priority support",
  "section.pricing.feature.custom": "Customization & SLA",
  "section.faq.title": "Frequently Asked Questions",
  "section.faq.q1": "Can I import my projects from another tool?",
  "section.faq.a1": "Yes! We offer automated import tools for most popular project management software like Trello, Asana, and Monday.com. Our support team can also help with custom migrations.",
  "section.faq.q2": "Can I use my own branding on the client portal?",
  "section.faq.a2": "With our Pro and Agency plans, you can host your client portal on your own domain (e.g., portal.youragency.com), use your brand colors, and remove all Netrise branding.",
  "section.faq.q3": "Is there a free trial?",
  "section.faq.a3": "Yes, we offer a 14-day full-featured free trial on all plans. No credit card is required to start your trial.",
  "section.faq.q4": "Can I change my plan later?",
  "section.faq.a4": "Absolutely. You can upgrade or downgrade your plan at any time from your billing settings. Upgrades take effect immediately.",
  "cta.title": "Ready to streamline your agency?",
  "cta.subtitle": "Join thousands of agencies already using Netrise to scale with less friction.",
  "cta.primary": "Start Free Trial",
  "cta.secondary": "Book a Demo",
  "footer.tagline": "The definitive management platform for creative agencies. Built by agency owners, for agency owners.",
  "footer.product": "Product",
  "footer.company": "Company",
  "footer.legal": "Legal",
  "footer.features": "Features",
  "footer.roadmap": "Roadmap",
  "footer.integrations": "Integrations",
  "footer.about": "About Us",
  "footer.careers": "Careers",
  "footer.contact": "Contact",
  "footer.privacy": "Privacy Policy",
  "footer.terms": "Terms of Service",
  "footer.cookies": "Cookie Policy",
  "footer.copyright": "© {year} Netrise. All rights reserved.",
  "a11y.skipToContent": "Skip to main content",
  "a11y.menuOpen": "Open navigation menu",
  "a11y.menuClose": "Close navigation menu",
  "a11y.faqExpand": "Expand answer",
  "a11y.faqCollapse": "Collapse answer",
  "a11y.themeToDark": "Switch to dark theme",
  "a11y.themeToLight": "Switch to light theme",
  "a11y.language": "Language",
  "a11y.setLanguage": "Change language to {lang}",
  "login.title": "Welcome to Netrise",
  "login.subtitle": "Please enter your details to sign in.",
  "login.registerTitle": "Create account",
  "login.registerSubtitle": "Choose your role and enter your details.",
  "login.roleLabel": "Role",
  "login.roleAgency": "Agency",
  "login.roleCloser": "Closer",
  "login.roleFreelancer": "Freelancer",
  "login.firstName": "First name",
  "login.firstNamePlaceholder": "Your first name",
  "login.lastName": "Last name",
  "login.lastNamePlaceholder": "Your last name",
  "login.email": "Email address",
  "login.emailPlaceholder": "name@company.com",
  "login.password": "Password",
  "login.passwordPlaceholder": "Enter your password",
  "login.confirmPassword": "Confirm password",
  "login.confirmPasswordPlaceholder": "Repeat password",
  "login.forgotPassword": "Forgot password?",
  "login.rememberMe": "Remember me for 30 days",
  "login.submit": "Sign In",
  "login.submitRegister": "Create account",
  "login.orContinue": "Or continue with",
  "login.google": "Google",
  "login.sso": "SSO",
  "login.noAccount": "Don't have an account?",
  "login.createAccount": "Create account",
  "login.hasAccount": "Already have an account?",
  "login.signIn": "Sign in",
  "login.leftHeadline": "The platform for agencies, closers and freelancers who scale.",
  "login.leftSubline": "The platform where you find leads, they close them, and you get clients.",
  "login.leftFeature1.title": "Verified Opportunities",
  "login.leftFeature1.desc": "Access exclusive roles and high-intent sales leads.",
  "login.leftFeature2.title": "Automated Payments",
  "login.leftFeature2.desc": "Handle commissions and invoices with one click.",
  "login.leftTrust": "Trusted by sales leaders globally.",
  "login.validation.emailRequired": "Email is required.",
  "login.validation.emailInvalid": "Please enter a valid email.",
  "login.validation.passwordRequired": "Password is required.",
  "login.validation.passwordMin": "At least 8 characters.",
  "login.validation.passwordMatch": "Passwords do not match.",
  "login.validation.roleRequired": "Please select a role.",
  "login.validation.firstNameRequired": "First name is required.",
  "login.validation.lastNameRequired": "Last name is required.",
  "login.register.success": "Account created. Check your email to verify your account.",
  "login.register.error": "Error creating account. Please try again.",
  "login.register.errorEmailTaken": "This email is already registered. Please sign in with your account.",
  "login.register.sending": "Creating account...",
  "login.login.error": "Error signing in. Please try again.",
  "login.login.invalid": "Incorrect email or password.",
  "profile.title": "Complete profile",
  "profile.heading": "Almost there, {name}",
  "profile.subtitle": "Complete your professional profile to connect with agencies and closers.",
  "profile.percentDone": "complete",
  "profile.saveLater": "Save and continue later",
  "profile.completeProfile": "Complete profile",
  "profile.whyComplete": "Why complete your profile?",
  "profile.whyComplete1": "Complete profiles get more opportunities.",
  "profile.whyComplete2": "Appear in search results for your niche.",
  "profile.photo": "Profile photo",
  "profile.photoOptional": "Optional",
  "profile.photoDrop": "Drag an image here or",
  "profile.photoSelect": "select a file",
  "profile.bannerPhoto": "Banner photo",
  "profile.bannerPhotoOptional": "Optional. Shown in the profile header.",
  "profile.bannerPhotoDrop": "Drag an image here or",
  "profile.bannerPhotoSelect": "select a file",
  "profile.agencyName": "Agency name",
  "profile.website": "Website",
  "profile.country": "Country",
  "profile.city": "City",
  "profile.services": "Services",
  "profile.servicesTag": "Add service",
  "profile.niches": "Niches",
  "profile.nichesTag": "Add niche",
  "profile.citiesOperate": "Cities where you operate",
  "profile.citiesOperateTag": "Add city",
  "profile.avgTicket": "Average ticket",
  "profile.commissionCloser": "Negotiable commission for closer",
  "profile.tradeName": "Trade name",
  "profile.tradeNameOptional": "Optional",
  "profile.portfolio": "Website / portfolio",
  "profile.languages": "Languages",
  "profile.languagesTag": "Add language",
  "profile.salesExperience": "Sales experience",
  "profile.salesSpecialties": "Sales specialties",
  "profile.salesSpecialtiesTag": "Add specialty",
  "profile.industries": "Industries you sell well in",
  "profile.industriesTag": "Add industry",
  "profile.avgTicketClose": "Average ticket you usually close",
  "profile.minCommission": "Minimum expected commission",
  "profile.salesRoleType": "Type of sales role",
  "profile.availability": "Availability",
  "profile.professionalProfile": "Professional profile",
  "profile.professionalBio": "Professional Bio",
  "profile.bioPlaceholder": "Briefly describe your experience, industry focus, and top achievements...",
  "profile.bioSuggestion": "Suggested: 200-500 characters for best engagement.",
  "profile.settings": "Settings",
  "profile.edit": "Edit",
  "profile.save": "Save",
  "profile.cancel": "Cancel",
  "profile.view.aboutUs": "About us",
  "profile.view.webPortfolio": "Web portfolio",
  "profile.view.viewAll": "View all",
  "profile.view.activeJobs": "Active job offers",
  "profile.view.clientTestimonials": "Client testimonials",
  "profile.view.readyToScale": "Ready to scale?",
  "profile.view.bookCall": "Schedule a call",
  "profile.view.messageAgency": "Message agency",
  "profile.view.ourTopClosers": "Our top closers",
  "profile.view.viewAllClosers": "View all closers",
  "profile.view.location": "Location",
  "profile.view.projectsCompleted": "Projects completed",
  "profile.view.revenueGenerated": "Revenue generated",
  "profile.view.clientRetention": "Client retention",
  "profile.view.activeClosers": "Active closers",
  "profile.view.coreExpertise": "Core expertise",
  "profile.view.trackRecord": "Track record",
  "profile.view.totalJobs": "Total jobs",
  "profile.view.hoursWorked": "Hours worked",
  "profile.view.agencyPartner": "Agency partner",
  "profile.view.collaborationInquiry": "Collaboration inquiry",
  "profile.view.aboutMe": "About me",
  "profile.view.portfolio": "Portfolio",
  "profile.view.servicePackages": "Service packages",
  "profile.view.message": "Message",
  "profile.view.hireMe": "Hire me",
  "profile.view.negotiate": "Negotiate",
  "profile.view.scheduleCall": "Schedule call",
  "profile.view.professionalOverview": "Professional overview",
  "profile.view.coreSpecializations": "Core specializations",
  "profile.view.introVideo": "Intro video",
  "profile.view.scheduleInterview": "Schedule interview",
  "profile.view.availableTimes": "Available times",

  "dashboard.nav.dashboard": "Dashboard",
  "dashboard.nav.perfil": "Profile",
  "dashboard.nav.explora": "Explore",
  "dashboard.nav.mensajes": "Messages",
  "dashboard.nav.feed": "Feed and notifications",
  "dashboard.nav.notificaciones": "Notifications",
  "dashboard.nav.equipo": "Team",
  "dashboard.nav.trabajos": "Jobs",
  "dashboard.nav.expand": "Expand menu",
  "dashboard.nav.collapse": "Collapse menu",
  "dashboard.nav.open": "Open menu",
  "dashboard.nav.close": "Close menu",

  "dashboard.card.totalRevenue": "Total revenue",
  "dashboard.card.avgConversion": "Avg conversion",
  "dashboard.card.totalMeetings": "Total meetings",
  "dashboard.card.leadsContacted": "Leads contacted",
  "dashboard.card.leadsThisMonth": "Leads generated this month",
  "dashboard.card.leadsPending": "Leads pending contact",
  "dashboard.card.avgTicket": "Average ticket",
  "dashboard.card.totalCommissions": "Total commissions to closers",
  "dashboard.card.freelancersActive": "Active freelancers",
  "dashboard.card.closersPending": "Closers pending payment",
  "dashboard.card.roi": "System ROI",
  "dashboard.card.activeAgencies": "Active agencies/freelancers",
  "dashboard.card.leadsAssigned": "Leads assigned",
  "dashboard.card.scheduledMeetings": "Scheduled meetings",
  "dashboard.card.meetingsThisMonth": "Total meetings this month",
  "dashboard.card.closedSales": "Closed sales",
  "dashboard.card.commissionsThisMonth": "Commissions this month",
  "dashboard.card.pendingCommissions": "Pending commissions",
  "dashboard.card.avgTicketClosed": "Avg ticket closed",
  "dashboard.card.closeRatio": "Close ratio",
  "dashboard.card.agencyProjects": "Agency projects",
  "dashboard.card.agenciesContacted": "Agencies contacted",
  "dashboard.card.agenciesWithClose": "Agencies contacted with close",
  "dashboard.chart.title": "Total revenue",
  "dashboard.chart.day": "Day",
  "dashboard.chart.week": "Week",
  "dashboard.chart.month": "Month",
  "dashboard.chart.sixMonths": "6 months",
  "dashboard.chart.year": "Year",
  "dashboard.card.vsPrevMonth": "vs previous month",
  "dashboard.table.export": "Export",
  "dashboard.table.exportCsv": "CSV",
  "dashboard.table.exportExcel": "Excel",
  "dashboard.table.exportJson": "JSON",
  "dashboard.table.import": "Import",
  "dashboard.table.importCsvOrExcelOrJson": "Import CSV, Excel or JSON",
  "dashboard.table.closers": "Closers",
  "dashboard.table.freelancers": "Freelancers",
  "dashboard.table.agencies": "Agencies",
  "dashboard.table.noData": "No data.",
  "dashboard.table.entriesPerPage": "Entries per page",
  "dashboard.table.of": "of",
  "dashboard.table.prev": "Previous",
  "dashboard.table.next": "Next",
  "dashboard.table.name": "Name",
  "dashboard.table.status": "Status",
  "dashboard.table.statusConnected": "Connected",
  "dashboard.table.statusDisconnected": "Disconnected",
  "dashboard.table.conversionRate": "Conversion rate",
  "dashboard.table.totalSalesEur": "Total sales (€)",
  "dashboard.table.meetings": "Meetings",
  "dashboard.table.pendingToPay": "Pending to pay",
  "dashboard.table.email": "Email",
  "dashboard.table.project": "Project",
  "dashboard.table.price": "Price",
  "dashboard.table.percentCompleted": "% completed",
  "dashboard.modal.close": "Close",
  "dashboard.modal.detail": "Breakdown",
  "dashboard.ranking.top3Freelancers": "Top 3 Freelancers",
  "dashboard.ranking.top3Closers": "Top 3 Closers",
  "dashboard.ranking.top3Agencies": "Top 3 Agencies",
  "dashboard.ranking.top3AgenciesByProjects": "Top 3 Agencies (by projects)",
  "dashboard.ranking.noData": "No data",
};
