import type { LiteralsMap } from "./types";

export const es: LiteralsMap = {
  "common.welcome": "Bienvenido",
  "common.cta": "Continuar",
  "common.loading": "Cargando...",
  "theme.light": "Claro",
  "theme.dark": "Oscuro",
  "nav.features": "Funcionalidades",
  "nav.pricing": "Precios",
  "nav.blog": "Blog",
  "nav.about": "Nosotros",
  "nav.login": "Iniciar sesión",
  "nav.getStarted": "Empezar",
  "hero.title": "Escala tu servicio creativo con confianza",
  "hero.titleHighlight": "servicio",
  "hero.subtitle": "La plataforma todo-en-uno para automatizar tu flujo de trabajo, gestionar clientes de alto valor y centralizar las operaciones de tu agencia en una interfaz clara.",
  "hero.ctaPrimary": "Prueba gratis",
  "hero.ctaSecondary": "Ver demo",
  "hero.trustedBy": "Con la confianza de más de 2000 propietarios de agencias",
  "section.why.tag": "Por qué elegirnos",
  "section.why.title": "Por qué las agencias nos necesitan",
  "section.why.subtitle": "Herramientas pensadas para que tu equipo cierre más y mejor.",
  "section.why.card1.title": "Escalar operaciones",
  "section.why.card1.desc": "Gestiona proyectos, equipos y clientes desde un solo lugar sin perder el control.",
  "section.why.card2.title": "Eficiencia de los closers",
  "section.why.card2.desc": "Automatiza reuniones, enlaces y recordatorios para que tus closers se centren en vender.",
  "section.why.card3.title": "Facturación automatizada",
  "section.why.card3.desc": "Cobros recurrentes, retainer y facturas en un solo flujo integrado.",
  "section.how.tag": "Cómo ganan los closers",
  "section.how.title": "Cómo ganan los closers",
  "section.how.subtitle": "Ofertas de calidad, reuniones ágiles y comisiones transparentes.",
  "section.how.card1.title": "Ofertas de calidad",
  "section.how.card1.desc": "Acceso a ofertas de agencia curadas, con embudos y material que convierten.",
  "section.how.card2.title": "Reuniones simplificadas",
  "section.how.card2.desc": "Enlaces Zoom automáticos, sincronización con calendario y recordatorios. Sin enlaces manuales ni citas perdidas.",
  "section.how.card3.title": "Comisiones transparentes",
  "section.how.card3.desc": "Seguimiento de ingresos en tiempo real. Visibilidad de comisiones, pagos y bonos en tu panel.",
  "section.freelancers.tag": "Para freelancers",
  "section.freelancers.title": "Cómo ayudamos a los freelancers",
  "section.freelancers.subtitle": "Herramientas para que trabajes solo pero no aislado: proyectos, facturación y presencia profesional.",
  "section.freelancers.card1.title": "Todo en un solo sitio",
  "section.freelancers.card1.desc": "Gestiona proyectos, clientes y facturación desde una sola plataforma sin cambiar de herramienta.",
  "section.freelancers.card2.title": "Facturación sin fricción",
  "section.freelancers.card2.desc": "Crea facturas, cobros recurrentes y recordatorios automáticos. Cobra a tiempo con menos papeleo.",
  "section.freelancers.card3.title": "Imagen profesional",
  "section.freelancers.card3.desc": "Portal para clientes, propuestas y entregas en un solo lugar. Parece una agencia, sin la complejidad.",
  "section.everything.title": "Todo lo que necesitas para escalar",
  "section.everything.subtitle": "Gestión de proyectos, portal para clientes y facturación en una sola plataforma.",
  "section.everything.card1.title": "Gestión de proyectos",
  "section.everything.card1.desc": "Seguimiento de tareas, hitos y flujos con tableros y diagramas de Gantt para equipos de diseño.",
  "section.everything.card2.title": "Portal white-label",
  "section.everything.card2.desc": "Portal con tu marca donde los clientes revisan diseños, dan feedback y aprueban hitos.",
  "section.everything.card3.title": "Facturación automatizada",
  "section.everything.card3.desc": "Suscripciones, retainer e facturas por proyecto. Cobra a tiempo con integraciones de pago.",
  "section.pricing.title": "Elige tu plan de crecimiento",
  "section.pricing.subtitle": "Planes para cada etapa de tu agencia.",
  "section.pricing.starter.label": "Agencia pequeña",
  "section.pricing.starter.name": "Starter",
  "section.pricing.starter.desc": "Ideal para freelancers que están montando su agencia.",
  "section.pricing.starter.cta": "Empezar",
  "section.pricing.pro.label": "Equipos en crecimiento",
  "section.pricing.pro.name": "Pro Agency",
  "section.pricing.pro.desc": "Todo lo que necesitas para gestionar un negocio de diseño serio.",
  "section.pricing.pro.cta": "Elegir plan",
  "section.pricing.pro.badge": "Más popular",
  "section.pricing.enterprise.label": "Gran empresa",
  "section.pricing.enterprise.name": "Enterprise",
  "section.pricing.enterprise.desc": "Funcionalidades a medida para agencias que escalan rápido.",
  "section.pricing.enterprise.cta": "Contactar ventas",
  "section.pricing.feature.projects": "Proyectos ilimitados",
  "section.pricing.feature.portal": "Portal de cliente",
  "section.pricing.feature.billing": "Facturación automática",
  "section.pricing.feature.support": "Soporte por email",
  "section.pricing.feature.priority": "Soporte prioritario",
  "section.pricing.feature.custom": "Personalización y SLA",
  "section.faq.title": "Preguntas frecuentes",
  "section.faq.q1": "¿Puedo importar mis proyectos desde otra herramienta?",
  "section.faq.a1": "Sí. Ofrecemos importación automática desde herramientas como Trello, Asana y Monday.com. El equipo de soporte también puede ayudarte con migraciones personalizadas.",
  "section.faq.q2": "¿Puedo usar mi propia marca en el portal de clientes?",
  "section.faq.a2": "Con los planes Pro y Agency puedes alojar el portal en tu dominio (p. ej. portal.tuagencia.com), usar tus colores y quitar la marca Netrise.",
  "section.faq.q3": "¿Hay prueba gratuita?",
  "section.faq.a3": "Sí. Ofrecemos 14 días de prueba con todas las funciones en todos los planes. No hace falta tarjeta para empezar.",
  "section.faq.q4": "¿Puedo cambiar de plan más adelante?",
  "section.faq.a4": "Sí. Puedes subir o bajar de plan cuando quieras desde la facturación. Las subidas se aplican al instante.",
  "cta.title": "¿Listo para simplificar tu agencia?",
  "cta.subtitle": "Únete a miles de agencias que ya usan Netrise para escalar con menos fricción.",
  "cta.primary": "Prueba gratis",
  "cta.secondary": "Reservar demo",
  "footer.tagline": "La plataforma definitiva para agencias creativas. Hecha por agencias, para agencias.",
  "footer.product": "Producto",
  "footer.company": "Empresa",
  "footer.legal": "Legal",
  "footer.features": "Funcionalidades",
  "footer.roadmap": "Roadmap",
  "footer.integrations": "Integraciones",
  "footer.about": "Nosotros",
  "footer.careers": "Carreras",
  "footer.contact": "Contacto",
  "footer.privacy": "Política de privacidad",
  "footer.terms": "Términos de servicio",
  "footer.cookies": "Política de cookies",
  "footer.copyright": "© {year} Netrise. Todos los derechos reservados.",
  "a11y.skipToContent": "Saltar al contenido principal",
  "a11y.menuOpen": "Abrir menú de navegación",
  "a11y.menuClose": "Cerrar menú de navegación",
  "a11y.faqExpand": "Desplegar respuesta",
  "a11y.faqCollapse": "Contraer respuesta",
  "a11y.themeToDark": "Activar tema oscuro",
  "a11y.themeToLight": "Activar tema claro",
  "a11y.language": "Idioma",
  "a11y.setLanguage": "Cambiar idioma a {lang}",
  "login.title": "Bienvenido a Netrise",
  "login.subtitle": "Introduce tus datos para iniciar sesión.",
  "login.registerTitle": "Crear cuenta",
  "login.registerSubtitle": "Elige tu rol e introduce tus datos.",
  "login.roleLabel": "Rol",
  "login.roleAgency": "Agencia",
  "login.roleCloser": "Closer",
  "login.roleFreelancer": "Freelancer",
  "login.firstName": "Nombre",
  "login.firstNamePlaceholder": "Tu nombre",
  "login.lastName": "Apellidos",
  "login.lastNamePlaceholder": "Tus apellidos",
  "login.email": "Correo electrónico",
  "login.emailPlaceholder": "nombre@empresa.com",
  "login.password": "Contraseña",
  "login.passwordPlaceholder": "Introduce tu contraseña",
  "login.confirmPassword": "Repetir contraseña",
  "login.confirmPasswordPlaceholder": "Repite la contraseña",
  "login.forgotPassword": "¿Olvidaste la contraseña?",
  "login.rememberMe": "Recordarme 30 días",
  "login.submit": "Iniciar sesión",
  "login.submitRegister": "Crear cuenta",
  "login.orContinue": "O continuar con",
  "login.google": "Google",
  "login.sso": "SSO",
  "login.noAccount": "¿No tienes cuenta?",
  "login.createAccount": "Crear cuenta",
  "login.hasAccount": "¿Ya tienes cuenta?",
  "login.signIn": "Iniciar sesión",
  "login.leftHeadline": "La plataforma para agencias, closers y freelancers que escalan.",
  "login.leftSubline": "La plataforma en la que encuentras leads, los cierran y obtienes clientes.",
  "login.leftFeature1.title": "Oportunidades verificadas",
  "login.leftFeature1.desc": "Accede a roles exclusivos y leads de ventas con alta intención.",
  "login.leftFeature2.title": "Pagos automatizados",
  "login.leftFeature2.desc": "Gestiona comisiones y facturas con un solo clic.",
  "login.leftTrust": "Con la confianza de líderes de ventas en todo el mundo.",
  "login.validation.emailRequired": "El correo es obligatorio.",
  "login.validation.emailInvalid": "Introduce un correo válido.",
  "login.validation.passwordRequired": "La contraseña es obligatoria.",
  "login.validation.passwordMin": "Mínimo 8 caracteres.",
  "login.validation.passwordMatch": "Las contraseñas no coinciden.",
  "login.validation.roleRequired": "Elige un rol.",
  "login.validation.firstNameRequired": "El nombre es obligatorio.",
  "login.validation.lastNameRequired": "Los apellidos son obligatorios.",
  "login.register.success": "Cuenta creada. Revisa tu correo para verificar la cuenta.",
  "login.register.error": "Error al crear la cuenta. Inténtalo de nuevo.",
  "login.register.errorEmailTaken": "Este correo ya está registrado. Inicia sesión con tu cuenta.",
  "login.register.sending": "Creando cuenta...",
  "login.login.error": "Error al iniciar sesión. Inténtalo de nuevo.",
  "login.login.invalid": "Correo o contraseña incorrectos.",
  "profile.title": "Completar perfil",
  "profile.heading": "Casi listo, {name}",
  "profile.subtitle": "Completa tu perfil profesional para conectar con agencias y closers.",
  "profile.percentDone": "completado",
  "profile.saveLater": "Guardar y continuar después",
  "profile.completeProfile": "Completar perfil",
  "profile.whyComplete": "¿Por qué completar el perfil?",
  "profile.whyComplete1": "Los perfiles completos reciben más oportunidades.",
  "profile.whyComplete2": "Aparece en las búsquedas de tu nicho.",
  "profile.photo": "Foto de perfil",
  "profile.photoOptional": "Opcional",
  "profile.photoDrop": "Arrastra una imagen aquí o",
  "profile.photoSelect": "selecciona un archivo",
  "profile.bannerPhoto": "Foto de banner",
  "profile.bannerPhotoOptional": "Opcional. Se muestra en la cabecera del perfil.",
  "profile.bannerPhotoDrop": "Arrastra una imagen aquí o",
  "profile.bannerPhotoSelect": "selecciona un archivo",
  "profile.agencyName": "Nombre de la agencia",
  "profile.website": "Website",
  "profile.country": "País",
  "profile.city": "Ciudad",
  "profile.services": "Servicios",
  "profile.servicesTag": "Añadir servicio",
  "profile.niches": "Nichos",
  "profile.nichesTag": "Añadir nicho",
  "profile.citiesOperate": "Ciudades donde opera",
  "profile.citiesOperateTag": "Añadir ciudad",
  "profile.avgTicket": "Ticket medio",
  "profile.commissionCloser": "Comisión negociable para closer",
  "profile.tradeName": "Nombre comercial",
  "profile.tradeNameOptional": "Opcional",
  "profile.portfolio": "Website / portfolio",
  "profile.languages": "Idiomas",
  "profile.languagesTag": "Añadir idioma",
  "profile.salesExperience": "Experiencia en ventas",
  "profile.salesSpecialties": "Especialidades de venta",
  "profile.salesSpecialtiesTag": "Añadir especialidad",
  "profile.industries": "Industrias donde vende bien",
  "profile.industriesTag": "Añadir industria",
  "profile.avgTicketClose": "Ticket promedio que suele cerrar",
  "profile.minCommission": "Comisión mínima esperada",
  "profile.salesRoleType": "Tipo de rol de ventas",
  "profile.availability": "Disponibilidad",
  "profile.professionalProfile": "Perfil profesional",
  "profile.professionalBio": "Biografía profesional",
  "profile.bioPlaceholder": "Describe brevemente tu experiencia, enfoque de industria y principales logros...",
  "profile.bioSuggestion": "Recomendado: 200-500 caracteres para una mejor visibilidad.",
  "profile.settings": "Ajustes",
  "profile.edit": "Editar",
  "profile.save": "Guardar",
  "profile.cancel": "Cancelar",
  "profile.view.aboutUs": "Sobre nosotros",
  "profile.view.webPortfolio": "Portfolio web",
  "profile.view.viewAll": "Ver todo",
  "profile.view.activeJobs": "Ofertas activas",
  "profile.view.clientTestimonials": "Testimonios",
  "profile.view.readyToScale": "¿Listo para escalar?",
  "profile.view.bookCall": "Reservar una llamada",
  "profile.view.messageAgency": "Mensaje a la agencia",
  "profile.view.ourTopClosers": "Nuestros mejores closers",
  "profile.view.viewAllClosers": "Ver todos los closers",
  "profile.view.location": "Ubicación",
  "profile.view.projectsCompleted": "Proyectos completados",
  "profile.view.revenueGenerated": "Ingresos generados",
  "profile.view.clientRetention": "Retención de clientes",
  "profile.view.activeClosers": "Closers activos",
  "profile.view.coreExpertise": "Competencias clave",
  "profile.view.trackRecord": "Historial",
  "profile.view.totalJobs": "Total trabajos",
  "profile.view.hoursWorked": "Horas trabajadas",
  "profile.view.agencyPartner": "Colaboración con agencias",
  "profile.view.collaborationInquiry": "Solicitar colaboración",
  "profile.view.aboutMe": "Sobre mí",
  "profile.view.portfolio": "Portfolio",
  "profile.view.servicePackages": "Paquetes de servicio",
  "profile.view.message": "Mensaje",
  "profile.view.hireMe": "Contrátame",
  "profile.view.negotiate": "Negociar",
  "profile.view.scheduleCall": "Programar llamada",
  "profile.view.professionalOverview": "Resumen profesional",
  "profile.view.coreSpecializations": "Especializaciones",
  "profile.view.introVideo": "Vídeo de presentación",
  "profile.view.scheduleInterview": "Programar entrevista",
  "profile.view.availableTimes": "Horarios disponibles",

  "dashboard.nav.dashboard": "Dashboard",
  "dashboard.nav.perfil": "Perfil",
  "dashboard.nav.explora": "Explora",
  "dashboard.nav.mensajes": "Mensajes",
  "dashboard.nav.feed": "Feed y notificaciones",
  "dashboard.nav.notificaciones": "Notificaciones",
  "dashboard.nav.equipo": "Equipo",
  "dashboard.nav.trabajos": "Trabajos",
  "dashboard.nav.expand": "Expandir menú",
  "dashboard.nav.collapse": "Contraer menú",
  "dashboard.nav.open": "Abrir menú",
  "dashboard.nav.close": "Cerrar menú",

  "dashboard.card.totalRevenue": "Ingresos totales",
  "dashboard.card.avgConversion": "Conversión media",
  "dashboard.card.totalMeetings": "Reuniones totales",
  "dashboard.card.leadsContacted": "Leads contactados",
  "dashboard.card.leadsThisMonth": "Leads generados este mes",
  "dashboard.card.leadsPending": "Leads pendientes de contactar",
  "dashboard.card.avgTicket": "Ticket medio",
  "dashboard.card.totalCommissions": "Comisiones totales a closers",
  "dashboard.card.freelancersActive": "Freelancers activos",
  "dashboard.card.closersPending": "Closers pendientes de cobro",
  "dashboard.card.roi": "ROI del sistema",
  "dashboard.card.activeAgencies": "Agencias/Freelancers activos",
  "dashboard.card.leadsAssigned": "Leads asignados",
  "dashboard.card.scheduledMeetings": "Reuniones programadas",
  "dashboard.card.meetingsThisMonth": "Reuniones totales del mes",
  "dashboard.card.closedSales": "Ventas cerradas",
  "dashboard.card.commissionsThisMonth": "Comisiones generadas este mes",
  "dashboard.card.pendingCommissions": "Comisiones pendientes de pago",
  "dashboard.card.avgTicketClosed": "Ticket medio cerrado",
  "dashboard.card.closeRatio": "Ratio de cierre",
  "dashboard.card.agencyProjects": "Proyectos para agencias",
  "dashboard.card.agenciesContacted": "Agencias contactadas",
  "dashboard.card.agenciesWithClose": "Agencias contactadas con cierre",
  "dashboard.chart.title": "Ingresos totales",
  "dashboard.chart.day": "Día",
  "dashboard.chart.week": "Semana",
  "dashboard.chart.month": "Mes",
  "dashboard.chart.sixMonths": "6 meses",
  "dashboard.chart.year": "Anual",
  "dashboard.card.vsPrevMonth": "vs mes anterior",
  "dashboard.table.export": "Exportar",
  "dashboard.table.exportCsv": "CSV",
  "dashboard.table.exportExcel": "Excel",
  "dashboard.table.exportJson": "JSON",
  "dashboard.table.import": "Importar",
  "dashboard.table.importCsvOrExcelOrJson": "Importar CSV, Excel o JSON",
  "dashboard.table.closers": "Closers",
  "dashboard.table.freelancers": "Freelancers",
  "dashboard.table.agencies": "Agencias",
  "dashboard.table.noData": "No hay datos.",
  "dashboard.table.entriesPerPage": "Entradas por página",
  "dashboard.table.of": "de",
  "dashboard.table.prev": "Anterior",
  "dashboard.table.next": "Siguiente",
  "dashboard.table.name": "Nombre",
  "dashboard.table.status": "Estado",
  "dashboard.table.statusConnected": "Conectado",
  "dashboard.table.statusDisconnected": "Desconectado",
  "dashboard.table.conversionRate": "Tasa de conversión",
  "dashboard.table.totalSalesEur": "Ventas totales (€)",
  "dashboard.table.meetings": "Reuniones",
  "dashboard.table.pendingToPay": "Pendiente de pagar",
  "dashboard.table.email": "Email",
  "dashboard.table.project": "Proyecto",
  "dashboard.table.price": "Precio",
  "dashboard.table.percentCompleted": "% completado",
  "dashboard.modal.close": "Cerrar",
  "dashboard.modal.detail": "Desglose",
  "dashboard.ranking.top3Freelancers": "Top 3 Freelancers",
  "dashboard.ranking.top3Closers": "Top 3 Closers",
  "dashboard.ranking.top3Agencies": "Top 3 Agencias",
  "dashboard.ranking.top3AgenciesByProjects": "Top 3 Agencias (por proyectos)",
  "dashboard.ranking.noData": "Sin datos",
};
